[package]
name = "minecraft_client_vk_shaders"
version = "0.1.0"
edition = "2024"

[features]
default = [ "shader_code" ]
shader_code = []
# `vulkano` dependency crates are in the main `Cargo.toml`
vulkano = []

[lib]
crate-type = [ "dylib" ]

[dependencies]
cfg-if = "1.0"
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu.git", rev = "20052f8" }
bitfield = "0.19"
