[package]
name = "hypercubed_resources"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = [
    # Dependencies
    "dep:image",
    "dep:zip",
    # Dependency features
    "ahash/default",
    "ahash/serde",
    "anyhow/default",
    "bimap/default",
    "hypercubed_core/default",
    "once_cell/default",
    "portable_std/default",
    "thiserror/default",
]

# Data embedding
use_embedded_cache = []

[dependencies]
ahash.workspace = true
anyhow.workspace = true
bimap.workspace = true
bitfield.workspace = true
hypercubed_core.workspace = true
guillotiere.workspace = true
image = { workspace = true, features = ["png"], optional = true }
indexmap = { workspace = true, features = ["serde"] }
log.workspace = true
miniz_oxide.workspace = true
nalgebra.workspace = true
once_cell.workspace = true
portable_std.workspace = true
postcard.workspace = true
protocol_derive.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
smallstr.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tracing = { workspace = true, features = ["attributes"] }
zip = { workspace = true, optional = true }
