[package]
name = "hypercubed_resources"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
std = [
    # Dependencies
    "dep:image",
    "dep:zip",
    # Dependency features
    "ahash/default",
    "ahash/serde",
    "anyhow/default",
    "bimap/default",
    "portable_std/default",
    "thiserror/default",
]
# Unfortunately lazy_static has a `no_std` feature, not a `std` feature, so
# we need this as a separate feature.
# Can be removed once we've removed lazy_static.
no_std = ["lazy_static/spin_no_std"]

# Data embedding
use_embedded_cache = []

[dependencies]
ahash.workspace = true
anyhow.workspace = true
bimap.workspace = true
bitfield.workspace = true
image = { workspace = true, features = ["png"], optional = true }
indexmap = { workspace = true, features = ["serde"] }
lazy_static.workspace = true
log.workspace = true
miniz_oxide.workspace = true
nalgebra.workspace = true
portable_std.workspace = true
postcard.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_repr.workspace = true
smallstr.workspace = true
smallvec.workspace = true
thiserror.workspace = true
zip = { workspace = true, optional = true }
