[workspace]
members = [
    "crates/protocol_derive",
    "crates/vulkan_prelude",
    "crates/hypercubed_resources",
    "crates/hypercubed_portable_std",
]
exclude = [
    "crates/hypercubed_vk_shaders",
    "crates/hypercubed_vk_shaders/builder",
    "crates/bimap-rs",
    "crates/cesu8-rs",
    "crates/CrabNBT",
    "crates/egui",
    "crates/egui_plot",
    "crates/foldhash",
    "crates/hashbrown",
    "crates/portable-atomic",
]

[workspace.dependencies]
ahash = { version = "0", default-features = false }
anyhow = { version = "1", default-features = false }
bimap = { version = "0.6", default-features = false, features = ["serde"] }
bincode = { version = "2", default-features = false, features = ["alloc", "derive", "serde"] }
bitfield = "0"
bitflags = "2"
bytemuck = { version = "1", features = ["derive"] }
cfg-if = "1"
embedded-io = { version = "0.6", features = ["alloc"] }
embedded-io-async = { version = "0.6", features = ["alloc"] }
foldhash = { version = "0", default-features = false }
hashbrown = { version = "0", features = ["serde"] }
indexmap = { version = "2", default-features = false }
lazy_static = "1"
log = "0"
miniz_oxide = "0"
once_cell = { version = "1", default-features = false, features = ["alloc"] }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
# If updating, also update in "crates/hypercubed_vk_shaders/Cargo.toml"
vulkano = { git = "https://github.com/vulkano-rs/vulkano", rev = "432955a" }
vulkan_prelude = { path = "crates/vulkan_prelude" }
smallstr = { version = "0", features = ["serde"] }
spirv-builder = { git = "https://github.com/Rust-GPU/rust-gpu.git", rev = "6a9ea3b" }
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu.git", rev = "6a9ea3b" }
zip = { version = "4", default-features = false, features = ["deflate"] }

[workspace.dependencies.image]
version = "0"
default-features = false
features = ["jpeg", "png"]

[workspace.dependencies.nalgebra]
version = "0.34"
default-features = false
features = ["libm", "macros", "serde", "serde-serialize-no-std"]

[workspace.dependencies.smallvec]
version = "1"
features = ["bincode", "const_generics", "const_new", "serde", "union"]

[workspace.dependencies.spin]
version = "0.9"
default-features = false
features = ["mutex", "spin_mutex", "portable_atomic"]

# Package

[package]
name = "hypercubed"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "staticlib"]
test = false
bench = false

[[bin]]
name = "hypercubed"

[features]
default = ["platform_winit", "graphics_backend_vulkan"]
# default = ["platform_winit", "graphics_backend_opengl"]
# default = ["platform_linux_drm", "graphics_backend_opengl"]

# Represents platforms which have full access to a standard library, and for which using `std`
# should be the default mechanism for most I/O.
# This includes using `std` for printing, file I/O, and networking.
full_std = [
    "mini_std",
]

# Represents platforms which don't require `no_std`, but that don't necessarily have access to a
# fully featured standard library.
# For example, the "wasm32-unknown-unknown" target has `std`, but it isn't useful for any I/O.
mini_std = [
    # Dependencies
    "dep:egui",
    "dep:egui_plot",
    "dep:env_logger",
    "dep:image",
    "dep:petgraph",
    "dep:pollster",
    "dep:threadpool",
    # Dependency features
    "ahash/default",
    "ahash/serde",
    "anyhow/default",
    "bimap/default",
    "crab_nbt/default",
    "foldhash/default",
    "indexmap/default",
    "once_cell/default",
    "nalgebra/serde-serialize",
    "nom/default",
    "nom_locate/default",
    "portable_std/default",
    "rand/default",
    "resources/default",
    "serde/default",
    "tracing/default",
    "tracing-subscriber/default",
    "uuid/default",
    "uuid/v4",
]

mimalloc = ["dep:mimalloc"]
protocol_verbose = ["full_std"]
tracy = ["dep:tracing-tracy"]

# Data embedding

use_embedded_cache = ["resources/use_embedded_cache"]
embed_vanilla_cache = ["use_embedded_cache"]

# Graphics backends

graphics_backend_wgpu = [
    # Other features
    "platform_winit",
    "mimalloc",
    # Dependencies
    "dep:wgpu",
]

graphics_backend_vulkan = [
    # Other features
    "platform_winit",
    "mimalloc",
    # Dependencies
    "dep:vulkano",
    "dep:vulkan_prelude",
    "dep:hypercubed_vk_shaders",
    "resources/luma_textures",
]

graphics_backend_opengl = [
    # Other features
    "full_std",
    # Dependencies
    "dep:glutin",
]

graphics_backend_software = [
    # Other features
    "platform_winit",
    "mimalloc",
    # Dependencies
    "dep:multiversion",
    "dep:pixels",
    "dep:wide",
    "dep:fast-srgb8",
]

# Alternative platforms

platform_winit = [
    # Other features
    "full_std",
    # Dependencies
    "dep:reqwest",
    "dep:winit",
    # Dependency features
    "glutin/default",
]

platform_linux_drm = [
    # Other features
    "full_std",
    # Dependencies
    "dep:clap",
    "dep:drm",
    "dep:egli",
    "dep:gbm",
    "dep:input",
    "dep:libseat",
    "dep:raw-window-handle",
    "dep:reqwest",
    "dep:rustix",
    # Dependency features
    "gbm/import-egl",
    "glutin/egl",
]

[build-dependencies]
anyhow.workspace = true
bincode.workspace = true
miniz_oxide.workspace = true

[build-dependencies.resources]
package = "hypercubed_resources"
path = "crates/hypercubed_resources"
features = ["std"]

[dependencies]
aes = "0.8"
ahash = { workspace = true }
anyhow = { version = "1", default-features = false }
bimap.workspace = true
bincode.workspace = true
bitfield.workspace = true
bitflags.workspace = true
bytebuffer = { version = "2", optional = true }
bytemuck.workspace = true
bytes = { version = "1", default-features = false }
cfb8 = { version = "0.8" }
cfg-if.workspace = true
clap = { version = "4.5", features = ["derive"], optional = true }
crab_nbt = { version = "0.2", default-features = false }
drm = { version = "0.14", optional = true }
egli = { git = "https://github.com/Nercury/egli-rs", rev = "723ee34", optional = true }
env_logger = { version = "0.10", optional = true }
fast-srgb8 = { version = "1.0", optional = true }
fixedbitset = "0.5"
foldhash.workspace = true
futures = { version = "0.3", default-features = false, features = ["async-await"] }
gbm = { version = "0.18", default-features = false, features = ["drm-support"], optional = true }
glutin = { version = "0.32", default-features = false, optional = true }
image = { workspace = true, optional = true }
indexmap.workspace = true
input = { version = "0.9", optional = true }
libseat = { version = "0.2", default-features = false, optional = true }
log.workspace = true
mimalloc = { version = "0.1", optional = true }
miniz_oxide.workspace = true
multiversion = { version = "0.8", optional = true }
nalgebra.workspace = true
nom = { version = "8", default-features = false, features = ["alloc"] }
nom_locate = { version = "5", default-features = false, features = ["alloc"] }
once_cell.workspace = true
ordered-float = { version = "4.5", default-features = false }
petgraph = { version = "0.6", optional = true }
pixels = { version = "0.15", optional = true }
pollster = { version = "0.3", optional = true }
protocol_derive = { version = "0.1.0", path = "crates/protocol_derive" }
rand = { version = "0.10.0-rc.5", default-features = false, features = ["std_rng"] }
raw-window-handle = { version = "0.6", optional = true }
reqwest = { version = "0.12", features = ["blocking", "json"], optional = true }
rustix = { version = "1.1", features = ["event"], optional = true }
serde.workspace = true
serde_json.workspace = true
sha1 = { version = "0.10", default-features = false }
smallvec.workspace = true
thiserror = { version = "2", default-features = false }
threadpool = { version = "1.8", optional = true }
tracing-subscriber = { version = "0.3", default-features = false, features = ["alloc"] }
tracing-tracy = { version = "0.11", optional = true }
tracing = { version = "0.1", default-features = false, features = ["attributes"] }
uuid = { version = "1", default-features = false, features = ["serde", "v3"] }
vulkan_prelude = { workspace = true, optional = true }
vulkano = { workspace = true, optional = true }
wgpu = { version = "24.0.3", optional = true }
wide = { version = "0.7", optional = true }
winit = { version = "0.30", optional = true }

[dependencies.egui]
version = "0.33"
default-features = false
features = ["bytemuck", "default_fonts"]
optional = true

[dependencies.egui_plot]
version = "0.34"
default-features = false
optional = true

[dependencies.rsa]
version = "0.10.0-rc.10"
default-features = false
features = ["encoding"]

[dependencies.hypercubed_vk_shaders]
path = "crates/hypercubed_vk_shaders"
features = ["vulkano"]
optional = true

[dependencies.portable_std]
package = "hypercubed_portable_std"
path = "crates/hypercubed_portable_std"
default-features = false

[dependencies.resources]
package = "hypercubed_resources"
path = "crates/hypercubed_resources"
default-features = false

# Profiles

[profile.dev]
opt-level = 1

[profile.dev.build-override]
opt-level = 1

[profile.dev-no-opt]
inherits = "dev"
opt-level = 0
panic = "unwind"
debug = "full"
strip = "none"

[profile.dev-no-opt.build-override]
opt-level = 1

[profile.release]
debug = false
lto = true
codegen-units = 1
panic = "abort"

[profile.release.build-override]
opt-level = 1

[profile.release-profiling]
inherits = "release"
lto = true
codegen-units = 8
panic = "abort"
debug = "full"
strip = "none"

[profile.release-profiling.build-override]
opt-level = 1
