[package]
name = "hypercubed_vk_shaders_redirect"
version = "0.1.0"
edition = "2024"

[features]
default = [ "shader_code" ]
shader_code = []
# `vulkano` dependency crates are in the main "hypercubed_vk_shaders/Cargo.toml"
vulkano = []

[lib]
crate-type = [ "dylib" ]

[dependencies]
cfg-if.workspace = true
spirv-std.workspace = true
bitfield.workspace = true
