/// Render info uniform buffer.
const RENDER_INFO: u32 = 0;
/// Lightmap storage buffer.
const LIGHTMAP: u32 = 1;
/// Basic sampler used for textures.
const BASIC_SAMPLER: u32 = 2;
/// Block and item atlas texture.
const BLOCK_ITEM_ATLAS: u32 = 3;
/// Custom block faces storage buffer.
const CUSTOM_BLOCK_FACES: u32 = 4;
/// Sun texture.
const SUN: u32 = 5;
/// Moon phases texture.
const MOON_PHASES: u32 = 6;
