[package]
name = "hypercubed_vanilla_data_gen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
nalgebra.workspace = true

[dependencies.portable_std]
package = "hypercubed_portable_std"
path = "../hypercubed_portable_std"

[dependencies.resources]
package = "hypercubed_resources"
path = "../hypercubed_resources"
