use super::crafting::Slot;
use crate::protocol::prelude::*;
use protocol_derive::Deserialize;

#[derive(Clone, Debug, Deserialize)]
#[repr(i32)]
pub enum Particle {
    AngryVillager = 0,
    Block {
        blockstate: VarInt,
    } = 1,
    BlockMarker {
        blockstate: VarInt,
    } = 2,
    Bubble = 3,
    Cloud = 4,
    Crit = 5,
    DamageIndicator = 6,
    DragonBreath = 7,
    DrippingLava = 8,
    FallingLava = 9,
    LandingLava = 10,
    DrippingWater = 11,
    FallingWater = 12,
    Dust {
        color: [f32; 3],
        scale: f32,
    } = 13,
    DustColorTransition {
        from_color: [f32; 3],
        to_color: [f32; 3],
        scale: f32,
    } = 14,
    Effect = 15,
    ElderGuardian = 16,
    EnchantedHit = 17,
    Enchant = 18,
    EndRod = 19,
    EntityEffect {
        color: [u8; 4],
    } = 20,
    ExplosionEmitter = 21,
    Explosion = 22,
    Gust = 23,
    SmallGust = 24,
    GustEmitterLarge = 25,
    GustEmitterSmall = 26,
    SonicBoom = 27,
    FallingDust {
        blockstate: VarInt,
    } = 28,
    Firework = 29,
    Fishing = 30,
    Flame = 31,
    Infested = 32,
    CherryLeaves = 33,
    SculkSoul = 34,
    SculkCharge {
        roll: f32,
    } = 35,
    SculkChargePop = 36,
    SoulFireFlame = 37,
    Soul = 38,
    Flash = 39,
    HappyVillager = 40,
    Composter = 41,
    Heart = 42,
    InstantEffect = 43,
    Item(Slot) = 44,
    Vibration {
        info: VibrationInfo,
        travel_time_ticks: VarInt,
    } = 45,
    ItemSlime = 46,
    ItemCobweb = 47,
    ItemSnowball = 48,
    LargeSmoke = 49,
    Lava = 50,
    Mycelium = 51,
    Note = 52,
    Poof = 53,
    Portal = 54,
    Rain = 55,
    Smoke = 56,
    WhiteSmoke = 57,
    Sneeze = 58,
    Spit = 59,
    SquidInk = 60,
    SweepAttack = 61,
    TotemOfUndying = 62,
    Underwater = 63,
    Splash = 64,
    Witch = 65,
    BubblePop = 66,
    CurrentDown = 67,
    BubbleColumnUp = 68,
    Nautilus = 69,
    Dolphin = 70,
    CampfireCosySmoke = 71,
    CampfireSignalSmoke = 72,
    DrippingHoney = 73,
    FallingHoney = 74,
    LandingHoney = 75,
    FallingNectar = 76,
    FallingSporeBlossom = 77,
    Ash = 78,
    CrimsonSpore = 79,
    WarpedSpore = 80,
    SporeBlossomAir = 81,
    DrippingObsidianTear = 82,
    FallingObsidianTear = 83,
    LandingObsidianTear = 84,
    ReversePortal = 85,
    WhiteAsh = 86,
    SmallFlame = 87,
    Snowflake = 88,
    DrippingDripstoneLava = 89,
    FallingDripstoneLava = 90,
    DrippingDripstoneWater = 91,
    FallingDripstoneWater = 92,
    GlowSquidInk = 93,
    Glow = 94,
    WaxOn = 95,
    WaxOff = 96,
    ElectricSpark = 97,
    Scrape = 98,
    Shriek {
        delay: VarInt,
    } = 99,
    EggCrack = 100,
    DustPlume = 101,
    TrialSpawnerDetection = 102,
    TrailSpawnerDetectionOminous = 103,
    VaultConnection = 104,
    DustPillar {
        blockstate: VarInt,
    } = 105,
    OminousSpawning = 106,
    RaidOmen = 107,
    TrialOmen = 108,
}

#[derive(Clone, Copy, Debug, Deserialize, PartialEq)]
#[repr(u8)]
pub enum VibrationInfo {
    BlockSource(Position) = 0,
    EntitySource { id: EntityId, eye_height: f32 } = 1,
}
