const SCALING_FACTOR: usize = 16;

pub const CASCADE_0_NUM_RAYS: usize = 16;
pub const CASCADE_0_RAY_LENGTH: f32 = 1.0 / 16.0;

pub const CASCADE_1_NUM_RAYS: usize = CASCADE_0_NUM_RAYS * SCALING_FACTOR;
pub const CASCADE_1_RAY_LENGTH: f32 = CASCADE_0_RAY_LENGTH * SCALING_FACTOR as f32;

// pub const CASCADE_2_NUM_RAYS: usize = CASCADE_1_NUM_RAYS * SCALING_FACTOR;
// pub const CASCADE_2_RAY_LENGTH: f32 = CASCADE_1_RAY_LENGTH * SCALING_FACTOR as f32;
//
// pub const CASCADE_3_NUM_RAYS: usize = CASCADE_2_NUM_RAYS * SCALING_FACTOR;
// pub const CASCADE_3_RAY_LENGTH: f32 = CASCADE_2_RAY_LENGTH * SCALING_FACTOR as f32;
