[package]
name = "hypercubed_vk_shaders"
version = "0.1.0"
edition = "2024"

[build-dependencies]
anyhow.workspace = true

[dependencies]
ahash.workspace = true
anyhow.workspace = true
bitfield.workspace = true
bytemuck.workspace = true
foldhash.workspace = true
once_cell = { workspace = true, default-features = true }
vulkano_prelude.workspace = true
vulkano.workspace = true
