# This is only used when this crate is included as a dependency for another crate.
# See `Cargo-RustGPU.toml`, which is used when building the actual shader.

[package]
name = "hypercubed_vk_shaders"
version = "0.1.0"
edition = "2024"

[features]
default = [ "vulkano" ]
shader_code = []
vulkano = []

[dependencies]
cfg-if = "1.0"
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu.git", rev = "20052f8" }
bitfield = "0.19"
vulkano = { path = "../vulkano/vulkano" }
vulkan_prelude = { path = "../vulkan_prelude" }
ahash = { version = "0", features = [ "serde" ] }
anyhow = "1"
bytemuck = { version = "1", features = [ "derive" ] }
foldhash = "0"
lazy_static = "1"
