[package]
name = "hypercubed_vk_shaders"
version = "0.1.0"
edition = "2024"

[build-dependencies]
anyhow.workspace = true

[dependencies]
bitfield.workspace = true
vulkano.workspace = true
vulkano_prelude.workspace = true
ahash.workspace = true
anyhow.workspace = true
bytemuck.workspace = true
foldhash.workspace = true
lazy_static.workspace = true
