[workspace]
members = ["builder", "builder/crate_redirect"]

[workspace.dependencies]
cfg-if = "1"
bitfield = "0"
spirv-builder = { git = "https://github.com/Rust-GPU/rust-gpu.git", rev = "20052f8" }
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu.git", rev = "20052f8" }
vulkano = { git = "https://github.com/vulkano-rs/vulkano", rev = "99ccf3c" }

[package]
name = "minecraft_client_vk_shaders"
version = "0.1.0"
edition = "2024"

[features]
default = ["vulkano"]
shader_code = []
vulkano = ["dep:vulkano"]

[dependencies]
cfg-if = { workspace = true }
spirv-std = { workspace = true }
bitfield = { workspace = true }
vulkano = { workspace = true, optional = true }
vulkan_prelude = { path = "../vulkan_prelude" }
ahash = { version = "0", features = ["serde"] }
anyhow = "1"
bytemuck = { version = "1", features = ["derive"] }
foldhash = "0"
lazy_static = "1"

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3
codegen-units = 16
