set shell := ["bash", "-uc"]
set windows-shell := ["cmd.exe", "/c"]

@_default:
    naga block_face.wgsl block_face.spv
    naga tinted_block_face.wgsl tinted_block_face.spv
    naga custom_block.wgsl custom_block.spv
    naga egui.wgsl egui.spv
    spirv-link --target-env vulkan1.1 block_face.spv tinted_block_face.spv custom_block.spv egui.spv
    spirv-opt out.spv -O -o optimised.spv
