use anyhow::{Context, anyhow};
use portable_std::{Atom, FastHashMap};

use resources::block::model::ModelRegistryBuilder;
use resources::block::{
    Data as BlockResourceData, Registration as BlockRegistration, Registry as BlockRegistry,
};

/// Loads the vanilla game data from either a vanilla client `minecraft.jar` file, or from an
/// extracted `assets`.
/// Can be used either to load the game data at run time, or from a build script to then embed the
/// resource data at compile time.
pub fn load_data() -> anyhow::Result<BlockResourceData> {
    let square_length = 16;
    let mut atlas_builder = resources::texture::AtlasBuilder::new(square_length);
    let mut model_registry_builder = ModelRegistryBuilder::new();
    let mut block_registry = BlockRegistry::new();
    register_into(
        &mut block_registry,
        &mut model_registry_builder,
        &mut atlas_builder,
    )?;
    let atlas = atlas_builder.finish();
    log::debug!("Atlas dimensions = {}x{}px", atlas.width, atlas.height);
    Ok(BlockResourceData {
        block_registry,
        model_registry: model_registry_builder.finish(),
        atlas,
    })
}

pub fn register_into(
    registry: &mut BlockRegistry,
    model_registry_builder: &mut ModelRegistryBuilder,
    texture_atlas_builder: &mut resources::texture::AtlasBuilder,
) -> anyhow::Result<()> {
    // Register blocks.
    {
        let start_time = std::time::Instant::now();
        /// Generated by `build.rs` from the `hypercubed_resources_vanilla_data_gen` crate.
        static COMPRESSED_POSTCARD: &[u8] = include_bytes!(concat!(
            env!("OUT_DIR"),
            "/blocks_registration_list.postcard.zlib"
        ));
        let uncompressed_postcard =
            miniz_oxide::inflate::decompress_to_vec_zlib(COMPRESSED_POSTCARD)
                .map_err(|err| anyhow!("Failed to decompress block postcard data - {err:#}"))?;
        let registrations: Vec<BlockRegistration> = {
            let start_time = std::time::Instant::now();
            let registrations: Vec<BlockRegistration> =
                postcard::from_bytes(&uncompressed_postcard)
                    .context("Error while deserialising registration list postcard data")?;
            log::debug!(
                "Block registration list load time: {:?}",
                std::time::Instant::now() - start_time
            );
            registrations
        };

        resources::block::register_blocks_from_list(
            registry,
            model_registry_builder,
            texture_atlas_builder,
            registrations,
        )?;
        log::debug!(
            "Block load time: {:?}",
            std::time::Instant::now() - start_time
        );
    }
    // Write out registry IDs to "entries.json", helpful for adding new blocks.
    // TODO: Move this behind a flag, gated behind an extra "debug" feature.
    // - Are these even in the right place anymore?
    #[cfg(debug_assertions)]
    {
        use core::fmt::Write;
        let mut block_ids = Vec::new();
        for (identifier, idx) in registry.data.identifier_map.iter() {
            let entry = &registry.data.entries[idx.0 as usize];
            block_ids.push((identifier, entry.blockstate_id_range.clone()));
        }
        block_ids.sort_by_key(|(_, range)| *range.start());
        let last_block = block_ids.len() - 1;
        let mut entries_string = String::from("[\n");
        for (i, (identifier, range)) in block_ids.into_iter().enumerate() {
            if i < last_block {
                writeln!(&mut entries_string, "  \"{identifier}: {range:?}\",")?;
            } else {
                writeln!(&mut entries_string, "  \"{identifier}: {range:?}\"")?;
            }
        }
        write!(&mut entries_string, "]")?;
        std::fs::write("entries.json", entries_string)?;
    }
    // Write out registry blockstate information to "blocks_rust.json".
    // Helpful for adding new blocks.
    // TODO: Move this to a startup flag, gated behind an extra "debug" feature.
    #[cfg(debug_assertions)]
    {
        use indexmap::{IndexMap, IndexSet};
        #[derive(Clone, Debug, serde::Serialize)]
        struct JsonBlock {
            #[serde(skip_serializing_if = "IndexMap::is_empty")]
            pub properties: IndexMap<Atom, IndexSet<Atom>>,
            pub states: Vec<JsonBlockstate>,
        }
        #[derive(Clone, Debug, serde::Serialize)]
        struct JsonBlockstate {
            #[serde(skip_serializing_if = "core::ops::Not::not")]
            pub default: bool,
            pub id: usize,
            #[serde(skip_serializing_if = "IndexMap::is_empty")]
            pub properties: IndexMap<Atom, Atom>,
        }
        // The Minecraft data generators sometimes break alphabetical order (why?) for properties,
        // so fix property sort order here for blocks which need it.
        let custom_ordering_map = {
            let mut map = FastHashMap::new();
            macro_rules! insert_entry {
                ($identifier:expr, [ $( $name:expr ),+ ]) => {
                    map.insert(resources::identifier!($identifier), vec![$( Atom::from($name), )+])
                };
            }
            insert_entry!("chest", ["type", "facing", "waterlogged"]);
            insert_entry!("moving_piston", ["type", "facing"]);
            insert_entry!("piston_head", ["type", "facing", "short"]);
            insert_entry!("trapped_chest", ["type", "facing", "waterlogged"]);
            map
        };
        let mut blocks = IndexMap::new();
        for (id, info) in registry.global_palette.iter().enumerate() {
            let identifier = registry
                .get_identifier_from_index(info.block_index)
                .unwrap();
            let block_entry = blocks.entry(identifier.to_string()).or_insert(JsonBlock {
                properties: IndexMap::new(),
                states: Vec::new(),
            });
            let mut properties: IndexMap<_, _> = info
                .properties
                .iter()
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect();
            if let Some(custom_ordering) = custom_ordering_map.get(identifier) {
                properties.sort_by_cached_key(|n1, _| {
                    custom_ordering.iter().position(|n2| n1 == n2).unwrap()
                });
            } else {
                properties.sort_unstable_keys();
            }
            for (property, value) in properties.iter() {
                let property_entry = block_entry
                    .properties
                    .entry(property.clone())
                    .or_insert(IndexSet::new());
                property_entry.insert(value.clone());
            }
            let default = registry.data[info.block_index]
                .default_blockstate
                .as_usize()
                == id;
            block_entry.states.push(JsonBlockstate {
                default,
                id,
                properties,
            });
        }
        blocks.sort_unstable_keys();
        let blocks_string = serde_json::to_string_pretty(&blocks)?;
        std::fs::write("blocks_rust.json", blocks_string)?;
    }

    Ok(())
}
